[package]
name = "lean_graph_theory"
version = "0.1"
lean_version = "leanprover-community/lean:3.18.4"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "84b450d42995e8d9ebf8a337525b6a5b862fb278"}
